# Generated by Django 2.2.4 on 2020-04-30 09:50

from django.db import migrations


def check_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2016:
            flat.new_building = False
            flat.save()
        else:
            flat.new_building = True
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0005_auto_20200430_1203'),
    ]

    operations = [
        migrations.RunPython(check_new_building),
    ]
