# Generated by Django 2.2.4 on 2020-05-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint',
        ),
        migrations.AddField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='property.Flat'),
        ),
    ]
