# Generated by Django 2.2.4 on 2020-05-03 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200503_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_flat', to=settings.AUTH_USER_MODEL, verbose_name='Лайки '),
        ),
    ]
