# Generated by Django 2.2.4 on 2020-05-03 13:39

from django.db import migrations


def change_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        old_number = flat.owners_phonenumber
        number_to_change = phonenumbers.parse(old_number, 'RU')
        flat.owner_phone_pure = phonenumbers.format_number(number_to_change, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0015_auto_20200503_1616'),
    ]

    operations = [
        migrations.RunPython(change_phone_number),
    ]
