# Generated by Django 2.2.4 on 2020-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200505_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(default='owner', max_length=30, verbose_name='ФИО владельца:'),
        ),
    ]
