# Generated by Django 2.2.4 on 2020-05-05 10:53

from django.db import migrations


def fill_in_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(full_name=flat.owner)
        Owner.objects.get_or_create(owner_number=flat.owners_phonenumber)
        Owner.objects.get_or_create(owner_phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0023_auto_20200505_1352'),
    ]

    operations = [
        migrations.RunPython(fill_in_owners),
    ]
