# Generated by Django 2.2.4 on 2020-05-06 02:51

from django.db import migrations


def fill_in_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(full_name=flat.owner, owner_number=flat.owners_phonenumber,
                                    owner_phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0026_auto_20200505_1902'),
    ]

    operations = [
        migrations.RunPython(fill_in_owners),
    ]
