# Generated by Django 2.2.4 on 2020-05-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20200506_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
