# Generated by Django 2.2.4 on 2020-05-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
