# Generated by Django 2.2.4 on 2020-05-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ФИО владельца:')),
                ('owner_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Номер владельца:')),
                ('owner_phone_pure', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Нормализованный номер владельца:')),
                ('owned_flat', models.ManyToManyField(related_name='by_flats', to='property.Flat')),
            ],
        ),
    ]
