# Generated by Django 2.2.4 on 2020-05-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_auto_20200507_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_phone_pure',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
