# Generated by Django 2.2.4 on 2020-05-11 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_auto_20200510_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='complaints', to='property.Flat'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
