# Generated by Django 2.2.4 on 2020-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_auto_20200513_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owned_flat',
            field=models.ManyToManyField(blank=True, related_name='by_flats', to='property.Flat', verbose_name='Квартиры владельца'),
        ),
    ]
